INSERT INTO INFO_USUARIO(CIDADE, DATA_ANIVERSARIO,DESCRICAO,ESTADO) VALUES
('Sao Paulo','1999-01-01','Padrao','SP'),
('Osasco','1998-01-01','Padrao','SP');

INSERT INTO REDE_SOCIAL (FACEBOOK,INSTAGRAM,TWITTER) VALUES
('face.com','insta.com','11912345678'),
('facebook.com','instagram.com','11987654321');

INSERT INTO USUARIO (EMAIL,NOME,NOTIFICADO,SENHA,INFO_USUARIO_ID_INFO_USUARIO, REDE_SOCIAL_ID_REDE_SOCIAL) VALUES
('mariana.sampaio@gmail.com', 'Mariana Sampaio', false, '$2a$10$z2//24hULq0N9e9okoWxa.lflLCqM0ApR0R3btqpxO.rf/8LpVBeW',1,1),
('luana.sampaio@gmail.com', 'Luana Sampaio', false, '$2a$10$z2//24hULq0N9e9okoWxa.lflLCqM0ApR0R3btqpxO.rf/8LpVBeW',2,2);

INSERT INTO INSTRUMENTO (INSTRUMENTO,NV_DOMINIO,TIPO_INSTRUMENTO,USUARIO_ID_USUARIO) VALUES
('guitarra','alto','corda',1),
('violao','alto','corda',2);

INSERT INTO GENERO (GENERO_MUSICAL,PREFERENCIA,USUARIO_ID_USUARIO) VALUES
('Rock','alto',1),
('Pop','alto',2);

INSERT INTO PUBLICACAO (CURTIDA,DATA_PUBLICACAO,REPORTE,TEXTO,USUARIO_ID_USUARIO) VALUES
(0,'2021-05-02',0,'Alguém a fim de fazer um som?',1),
(0,'2021-05-02',0,'Alguém querendo sair no final de semana?',2);

INSERT INTO MEDALHA (DATA_INICIO,NUM_CONVITES,NUM_CURTIDAS,NUM_PESQUISAS,NUM_PUBLICACOES,TODAS_INFOS,USUARIO_ID_USUARIO) VALUES
('2020-11-01',0,0,0,1,TRUE,1),
('2020-11-02',0,0,0,1,TRUE,2);

INSERT INTO REGISTRO_MEDALHA (REG_DATA_INICIO,REG_NUM_CONVITES,REG_NUM_CURTIDAS,REG_NUM_PESQUISAS,REG_NUM_PUBLICACOES,REG_TODAS_INFOS,USUARIO_ID_USUARIO) VALUES
(1,TRUE,1,1,1,1,1),
(1,TRUE,1,1,1,1,2);

INSERT INTO CONVITE (CONFIRMADO, DATA_CONVITE,ID_CONVIDADO,ID_CONVIDOU) VALUES
(true,'2021-05-01',1,2),
(true,'2021-05-02',2,1);